/* This file is generated by scripts/sync-modules.mjs. Do not edit by hand. */
import module01 from "./01_values_state_execution.md?raw";
import module02 from "./02_functions_recursion_induction.md?raw";
import module03 from "./03_abstraction_interfaces_adts.md?raw";
import module04 from "./04_logic_sets_relations_graphs_proof.md?raw";
import module05 from "./05_cost_models_algorithm_analysis.md?raw";
import module06 from "./06_representation_memory_sequences_linked.md?raw";
import module07 from "./07_stacks_queues_iteration_lazy.md?raw";
import module08 from "./08_hashing_dictionaries_sets_indexing.md?raw";
import module09 from "./09_trees_heaps_sorting_ordered.md?raw";
import module10 from "./10_graph_algorithms_network_models.md?raw";
import module11 from "./11_algorithm_design_paradigms.md?raw";
import module12 from "./12_modules_apis_types_dependencies.md?raw";
import module13 from "./13_specifications_testing_debugging_observability.md?raw";
import module14 from "./14_software_design_and_change.md?raw";
import module15 from "./15_files_serialization_packaging_delivery.md?raw";
import module16 from "./16_relational_data_transactions.md?raw";
import module17 from "./17_computer_architecture_execution_stack.md?raw";
import module18 from "./18_operating_systems_resource_mediation.md?raw";
import module19 from "./19_concurrency_parallelism.md?raw";
import module20 from "./20_networks_application_protocols.md?raw";
import module21 from "./21_async_distributed_systems.md?raw";
import module22 from "./22_security_privacy_trust_boundaries.md?raw";

export const moduleMarkdownBySlug: Readonly<Record<string, string>> = {
  "01-values-state-execution": module01,
  "02-functions-recursion-induction": module02,
  "03-abstraction-interfaces-adts": module03,
  "04-logic-sets-relations-graphs-proof": module04,
  "05-cost-models-algorithm-analysis": module05,
  "06-representation-memory-sequences-linked": module06,
  "07-stacks-queues-iteration-lazy": module07,
  "08-hashing-dictionaries-sets-indexing": module08,
  "09-trees-heaps-sorting-ordered": module09,
  "10-graph-algorithms-network-models": module10,
  "11-algorithm-design-paradigms": module11,
  "12-modules-apis-types-dependencies": module12,
  "13-specifications-testing-debugging-observability": module13,
  "14-software-design-and-change": module14,
  "15-files-serialization-packaging-delivery": module15,
  "16-relational-data-transactions": module16,
  "17-computer-architecture-execution-stack": module17,
  "18-operating-systems-resource-mediation": module18,
  "19-concurrency-parallelism": module19,
  "20-networks-application-protocols": module20,
  "21-async-distributed-systems": module21,
  "22-security-privacy-trust-boundaries": module22,
};
