import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("goal compliance is a generated compact truth surface with preserved history", async () => {
  const [source, matrix, history] = await Promise.all([
    readFile(new URL("../content/course/goal-compliance.v1.json", import.meta.url), "utf8").then(JSON.parse),
    readFile(new URL("../docs/GOAL_COMPLIANCE_MATRIX.md", import.meta.url), "utf8"),
    readFile(new URL("../docs/GOAL_COMPLIANCE_HISTORY.md", import.meta.url), "utf8"),
  ]);

  assert.match(
    matrix,
    /GENERATED by scripts\/generate-goal-compliance\.mjs from content\/course\/goal-compliance\.v1\.json/u,
  );
  assert.match(matrix, /Last successful full gate:/u);
  assert.doesNotMatch(matrix, /predates the current Draft head/u);
  assert.match(matrix, /Latest recorded content-bearing Draft check:/u);
  assert.match(matrix, /Latest recorded full-gate apparatus check:/u);
  assert.match(matrix, /Open red tests:/u);
  assert.match(matrix, /Open axe violations:/u);
  assert.match(matrix, /Open Dependabot alerts on/u);
  assert.match(matrix, /\| Requirement \| State \| Evidence path \| One open item \|/u);
  assert.match(matrix, /\[historical matrix\]\(GOAL_COMPLIANCE_HISTORY\.md\)/u);

  assert.ok(Array.isArray(source.requirements));
  assert.equal(
    (matrix.match(/^\| (?!---)(?!Requirement\b).+\| (?:complete|partial|open|unverified) \|/gmu) ?? []).length,
    source.requirements.length,
  );
  assert.match(history, /^# Atlas goal-compliance matrix/mu);
  assert.match(history, /historical release-hardening evidence matrix/u);
  assert.match(history, /registry-count clarification/iu);
});
