/* This file is generated by scripts/sync-modules.mjs. Do not edit by hand. */
import authoringModule31 from "./m31_optimization_information_workbook.v1.md?raw";
import authoringModule32 from "./m32_systems_languages_scientific_python_accelerators_workbook.v1.md?raw";
import authoringModule33 from "./m33_formal_languages_computability_complexity_workbook.v1.md?raw";
import authoringModule34 from "./m34_classical_ai_search_constraints_decision_workbook.v1.md?raw";
import authoringModule35 from "./m35_machine_learning_representation_workbook.v1.md?raw";
import authoringModule36 from "./m36_statistical_learning_theory_reliable_deep_learning_workbook.v1.md?raw";

export const authoringModuleMarkdownBySlug: Readonly<Record<string, string>> = {
  "31-optimization-information": authoringModule31,
  "32-systems-languages-scientific-python-accelerators": authoringModule32,
  "33-formal-languages-computability-complexity": authoringModule33,
  "34-classical-ai-search-constraints-decision": authoringModule34,
  "35-machine-learning-representation": authoringModule35,
  "36-statistical-learning-theory-reliable-deep-learning": authoringModule36,
};
